### PR TITLE
Librosa backend

### PR DESCRIPTION
**Pull request by alreadytaikeune**
# [Spleeter-282] - Using librosa as an alternative backend for stft computation

## Description

Tensorflow's implementation of stft and istft on CPU is extremely slow and glutton in memory. I implemented the possibility to defer these computations to librosa which results in faster inference on CPU and vastly diminished memory usage. The use of the backend can be controlled by an additional parameter on the command line, which defaults to the following logic:
- GPU acceleration available -> tensorflow backend for stfts
- GPU acceleration not available -> librosa backend for stfts.

## How this patch was tested

Ran the separate commands using all the different backend options and checked the consistencies of the outputs as well as the memory use.

### CODE REVIEW

**Comment by mmoussallam** [comment]
* bump the spleeter version in dockerfiles
* bump the tensorflow lib version to 1.15
* remove duplicate logs

**Comment by jaolan** [comment]
I tried to test your Librosa backend implementation, but it seems like the -w argument is unrecognized. How are you using the new stft_backend flag on the command line?

**Comment by alreadytaikeune** [comment]
Hi @jaolan, the option is -B or --stft-backend. You can pass "tensorflow", "librosa", or "auto" as parameter.

**Comment by jaolan** [comment]
Hi @alreadytaikeune, I have tried running this with your changes in the librosa branch, but --stft_backend and -B are unrecognized arguments for separate. I have tried running

> spleeter separate  -i audio_example.mp3 -p spleeter:4stems -o output --stft-backend librosa 

with no success. Is there any additional steps needed to follow before running? Thanks!

**Comment by alreadytaikeune** [comment]
Hi @jaolan can you show me a code snippet to reproduce the error? Thank's a lot.

**Comment by jaolan** [comment]
> Hi @jaolan can you show me a code snippet to reproduce the error? Thank's a lot.
This is the output I get upon trying 2 or 4 stems. Thanks for your help!
image

**Comment by alreadytaikeune** [comment]
Hi @jaolan I can't figure out which version of the `separator.py` file you are using because your stack trace doesn't seem to correspond to the current version (commit `3cba6985f410750f9704303668e4093dde29f7a3`) of the script. Can you show me the content of your `separator.py`? Thanks

**Comment by jaolan** [comment]
Hi @alreadytaikeune , here is the separator.py code: [https://gist.github.com/jaolan/c7c5be3dc2d3d5a4090dc65d67e3e165](url)

**Comment by alreadytaikeune** [comment]
I don't have the rights to access this.

**Comment by jaolan** [comment]
> I don't have the rights to access this.

Apologies, everything is working as intended after merge to master. Thanks!

**Pull request merged**
