### PR TITLE
Add Moises.ai reference to Readme file

### PR DESCRIPTION
**Pull request by geraldoramos**
# [Spleeter-readme] - Add Moises.ai reference to Readme file

## Description

Moises.ai runs Spleeter in a farm of servers and allow anyone to try it without installing anything. You can post a song and get back separated tracks back (2stems, 4stems or 5stems supported).

## How this patch was tested

No test required.

## Documentation link and external references

Not applicable

### CODE REVIEW

**Comment by Faylixe** [comment]
Hi, thanks for the PR.

Unfortunately I think we would not be able to reference your solution explicitly into this repository for legal reason (but still to be confirmed, meanwhile we won't either close or merge the PR :))

**Comment by geraldoramos** [comment]
Thanks, I've confirmed that this will not be possible (for understandable reasons) and I'm closing the PR.

**Comment by aidv** [comment]
@Faylixe If you add moises.ai, you also must add melody.ml and splitter.ai.

I'm against the comment "but still to be confirmed".[ You've stated here](https://github.com/deezer/spleeter/issues/94) that you will NOT promote any external projects because of copyright legal reasons.

Don't be corrupt.

**Comment by geraldoramos** [comment]
@aidv What are you talking about? It's clear that this PR is not going to be accepted. Deezer folks were kind enough to reach out to me telling it won't be promoted for legal reasons (Moises or any other).

I'm not sure why you complaining here since I voluntarily closed this PR once I heard from them.

Sorry, but I don't see any corruption here or even close...

**Comment by aidv** [comment]
@geraldoramos Democracy my friend. It's not about complaining, it's about keeping the project flourishing and healthy and I'm just saying that if one project is to be promoted, then all other projects should have an equal chance of promotion.

**Comment by geraldoramos** [comment]
Ok. :)

I surely agree with this. I assume if Spleeter's policy allowed the promotion of services, it would be a list of all services, not just mine. I was taking the first step towards it since I was one of the firsts to build a free service on top of this excellent library. Since it's not allowed, no action for this PR is needed, and I've closed it as soon as I heard about it.

**Comment by aidv** [comment]
I wonder how many are out there. Splitter, Moises, Melody. I bet we'll see a few more.

**Comment by doky** [comment]
We start the list all of services based on Spleeter ? And thank you all!

**Comment by geraldoramos** [comment]
> I wonder how many are out there. Splitter, Moises, Melody. I bet we'll see a few more.

Another one: https://vocali.se

**Comment by aidv** [comment]
@doky Yes. And thank you too for listening to the community.

**Comment by mmoussallam** [comment]
Hi @aidv,

As stated by Félix, we have talked and we don't think the Readme is the approriate place to reference services using spleeter. This is why this PR has been closed and similar ones will not be merged.

However, since there is a community need to list the services, I'll start a gitter thread where we can have the list. I'll actually be much easier to maintain there.

**Comment by aidv** [comment]
@mmoussallam sounds good.

**Comment by jnegreira** [comment]
Another one: https://es.split.band/ (in spanish)

**Pull request closed without merging**
